FROM node:9.5.0

WORKDIR /app

ADD package.json /app/package.json
RUN npm install

ADD . /app

ENV SERVER_URL http://localhost
ENV PUBLIC_SERVER_URL http://localhost
ENV APP_NAME Pettlyapp
ENV APP_ID myAppId
ENV MASTER_KEY ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQD0yHS5qUGuq+WfExy70MXcp1jLd9b7VrwJL6aUHAHrH1CIuTjmrdyGskcSqudRDfiXkvcZ8qDLobcGCbvmnUVS33GhqY0HNQihOwABHmhiUaEjTWg94bk0kDapdIEgeCyWPMT7Vv+lc1EJTWcPAnTIXktbQaRvE421jqRkgPrvuw==
ENV MAILGUN_API_KEY YOUR_MAILGUN_API_KEY
ENV MAILGUN_DOMAIN quanlabs.com
ENV MAILGUN_FROM_ADDRESS 'QuanLabs <info@quanlabs.com>'
ENV MAILGUN_TO_ADDRESS 'info@quanlabs.com'
ENV GOOGLE_MAPS_API_KEY AIzaSyAriq7j3uAojTvEgUK_fVSb2aZ7RPwsOg8
ENV PUSH_ANDROID_SENDER_ID YOUR_SENDER_ID
ENV PUSH_ANDROID_API_KEY YOUR_ANDROID_API_KEY
ENV PUSH_IOS_BUNDLE_ID com.quanlabs.nearme4
ENV MAX_UPLOAD_SIZE 20M
ENV DOKKU_LETSENCRYPT_EMAIL dev@quanlabs.com
#ENV NEW_RELIC_LICENSE_KEY YOUR_NEW_RELIC_LICENSE_KEY

CMD ["npm", "start"]